
version: "3.3"
services:
  postgres:
    image: postgres:13.4
    environment:
      POSTGRES_USER: "pgadmin"
      POSTGRES_PASSWORD: "pgpassword"
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"